CREATE TABLE IF NOT EXISTS pagamento (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT,
    status    VARCHAR(50)
);

-- Idempotência: um pedido gera no máximo um pagamento, mesmo com reentregas da mensagem
CREATE UNIQUE INDEX IF NOT EXISTS ux_pagamento_pedido_id ON pagamento (pedido_id);
